# Names and paths
dataset_name: example # E.g. STT or SDS
split_name: train # Name of the split, e.g. Train.
out_folder_base: main # Base_path

# Data Sources
tsv_paths: ["tests/assets/tsv-data-example/export_20211220_sample_10utterances copy.tsv"]
clips_folders: ["tests/assets/tsv-data-example/clips"]
partials: [1.0]

# Generate config
maintain_speaker_chance: 0.5
n_samples_per_srt: 16
overlap_chance: 0.6
max_overlap_chance: 0.2